name: ci

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]

    env:
      DENO_VERSION: 1.2.2
      RUST_VERSION: 1.45.0
      RUST_BACKTRACE: full

    steps:
      - name: Clone repository
        uses: actions/checkout@v1

      - name: Install rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ env.RUST_VERSION }}

      - name: Install Deno
        uses: denolib/setup-deno@master
        with:
          deno-version: ${{ env.DENO_VERSION }}

      - name: Log versions
        run: |
          deno --version
          rustc --version
          cargo --version

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |-
            ~/.cargo/registry
            ~/.cargo/git
            test_plugin/target/*/.*
            test_plugin/target/*/build
            test_plugin/target/*/deps
          key:
            ${{ matrix.os }}-${{ hashFiles('test_plugin//Cargo.lock') }}
          restore-keys: |
            ${{ matrix.os }}-

      - name: Build test_plugin
        working-directory: test_plugin
        run: cargo build

      - name: Test
        run: deno test -A --unstable
